import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { correlationRefs, requestIdFromHeaders } from "./correlation";
import { readRepoFile } from "../testing/repo-files";

describe("what ties one customer's journey together", () => {
  it("keeps the identifiers that are actually present", () => {
    assert.deepEqual(
      correlationRefs({ conversationId: "c-1", eventId: "e-1" }),
      { conversationId: "c-1", eventId: "e-1" },
    );
  });

  it("drops the absent ones instead of writing nulls", () => {
    // input_refs is read by eye when something has gone wrong. Five null keys
    // on every row makes the one that matters harder to find, not easier.
    assert.deepEqual(
      correlationRefs({ contactId: null, eventId: "e-1", leadId: undefined }),
      { eventId: "e-1" },
    );
    assert.deepEqual(correlationRefs({ eventId: "   " }), {});
    assert.deepEqual(correlationRefs(null), {});
    assert.deepEqual(correlationRefs(undefined), {});
  });

  it("ignores anything that is not a string", () => {
    const hostile = { eventId: 42, leadId: {} } as unknown as Parameters<
      typeof correlationRefs
    >[0];

    assert.deepEqual(correlationRefs(hostile), {});
  });
});

describe("a request id for work no customer started", () => {
  it("uses the one Vercel already stamps on every request", () => {
    assert.equal(
      requestIdFromHeaders(new Headers({ "x-vercel-id": "syd1::abc123" })),
      "syd1::abc123",
    );
  });

  it("falls back to the W3C trace id", () => {
    const traceparent = "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01";

    assert.equal(
      requestIdFromHeaders(new Headers({ traceparent })),
      "4bf92f3577b34da6a3ce929d0e0e4736",
    );
  });

  it("returns nothing rather than inventing an id", () => {
    // An id that correlates with nothing is worse than no id: it looks like
    // evidence.
    assert.equal(requestIdFromHeaders(new Headers()), null);
    assert.equal(
      requestIdFromHeaders(new Headers({ traceparent: "00-short-x-01" })),
      null,
    );
  });
});

/**
 * The gap this closes, asserted at the call sites.
 *
 * 530 inquiry notifications and 220 escalation alerts were generated by an
 * inbound message and recorded nothing that could be joined back to it. The
 * behaviour needs a live inbound message to exercise, so these assert the
 * wiring -- the same approach the address verification guards take.
 */
describe("an alert can be traced to the message that caused it", () => {
  it("records the correlation on every generated run", () => {
    const generation = readRepoFile(
      "apps/web/src/lib/ai/customer-message-generation.ts",
    );

    assert.match(generation, /\.\.\.correlationRefs\(input\.correlation\)/);
  });

  it("gives an escalation alert its contact, conversation and lead", () => {
    const escalation = readRepoFile(
      "apps/web/src/lib/escalation/urgent-escalation.ts",
    );

    assert.match(escalation, /correlation: \{\s*contactId: input\.contactId,/);
  });

  it("gives an inquiry notification the inbound event on both channels", () => {
    for (const file of [
      "apps/web/src/lib/integrations/inbound-sms.ts",
      "apps/web/src/lib/integrations/inbound-email-sync.ts",
    ]) {
      assert.match(
        readRepoFile(file),
        /correlation: \{[\s\S]{0,120}eventId:/,
        `${file} does not pass an eventId to notifyInboundInquiry`,
      );
    }
  });
});
